/* BOOT */
(async () => {
  const savedTheme = localStorage.getItem('dungeon-theme');
  if (savedTheme) document.documentElement.dataset.theme = savedTheme;
  updateTimerUI();
  document.getElementById('timerPhase').textContent = 'Listo';
  if (Notification.permission === 'granted') notifEnabled = true;
  await initDB();
  await handleSpotifyCallback();
  renderSpotifyWidget();
  loadRealWeather();
  updateDungeonClock();
  setInterval(updateDungeonClock, 60 * 1000);
  if (typeof handleGoogleFitCallback  === 'function') await handleGoogleFitCallback();
  if (typeof handleGoogleCalCallback  === 'function') await handleGoogleCalCallback();
  if (typeof syncGoogleFitSteps       === 'function') syncGoogleFitSteps();
  await migrateRarity();
  await resetDailyQuests();
  await resetRepeatQuests();
  await checkOverdueHP();
  if (typeof checkWagerExpiry === 'function') await checkWagerExpiry();
  updatePomGoalUI();
  restoreTimerState();
  checkStreakDanger();
  initPWA();
  initKanbanDrag();
  setInterval(renderSpells, 2 * 60 * 1000);
  setInterval(checkStreakDanger, 30 * 60 * 1000);
  showWelcomeScreen();
  initParticles();
  checkConnection();
  setInterval(checkConnection, 5 * 60 * 1000);
  initRPGSystems();
  checkDailySummary();
  checkWeeklyRetro();
  checkMorningBriefing();
  checkDeadlineAlerts();
  checkNightlyDiary();
  checkProphecyVerdict();
  if (typeof checkWeeklyPatternAnalysis === 'function') checkWeeklyPatternAnalysis();
  setInterval(() => {
    checkDailySummary(); checkWeeklyRetro(); checkDeadlineAlerts(); checkNightlyDiary(); checkProphecyVerdict();
    if (typeof checkWeeklyPatternAnalysis === 'function') checkWeeklyPatternAnalysis();
  }, 60 * 60 * 1000);
  updateFocusTodayChip();
})();