$map = @(
  @('F:\Dungeon\ARMAMENTO\Botas comun.png','F:\PROYECTOS\dungeon\images\arma_botas_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Botas epica.png','F:\PROYECTOS\dungeon\images\arma_botas_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Botas legendaria.png','F:\PROYECTOS\dungeon\images\arma_botas_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Botas mitica.png','F:\PROYECTOS\dungeon\images\arma_botas_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Botas raro.png','F:\PROYECTOS\dungeon\images\arma_botas_raro.png'),
  @('F:\Dungeon\ARMAMENTO\Casco comun.png','F:\PROYECTOS\dungeon\images\arma_casco_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Casco epico.png','F:\PROYECTOS\dungeon\images\arma_casco_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Casco legendario.png','F:\PROYECTOS\dungeon\images\arma_casco_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Casco mitico.png','F:\PROYECTOS\dungeon\images\arma_casco_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Casco raro.png','F:\PROYECTOS\dungeon\images\arma_casco_raro.png'),
  @('F:\Dungeon\ARMAMENTO\Dagas comun.png','F:\PROYECTOS\dungeon\images\arma_dagas_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Dagas epico.png','F:\PROYECTOS\dungeon\images\arma_dagas_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Dagas legendaria.png','F:\PROYECTOS\dungeon\images\arma_dagas_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Dagas mitico.png','F:\PROYECTOS\dungeon\images\arma_dagas_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Dagas raro.png','F:\PROYECTOS\dungeon\images\arma_dagas_raro.png'),
  @('F:\Dungeon\ARMAMENTO\Espada comun.png','F:\PROYECTOS\dungeon\images\arma_espada_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Espada epica.png','F:\PROYECTOS\dungeon\images\arma_espada_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Espada legendaria.png','F:\PROYECTOS\dungeon\images\arma_espada_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Espada mitica.png','F:\PROYECTOS\dungeon\images\arma_espada_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Espada rara.png','F:\PROYECTOS\dungeon\images\arma_espada_raro.png'),
  @('F:\Dungeon\ARMAMENTO\Grebas comun.png','F:\PROYECTOS\dungeon\images\arma_grebas_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Grebas epico.png','F:\PROYECTOS\dungeon\images\arma_grebas_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Grebas legendario.png','F:\PROYECTOS\dungeon\images\arma_grebas_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Grebas mitico.png','F:\PROYECTOS\dungeon\images\arma_grebas_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Grebas raro.png','F:\PROYECTOS\dungeon\images\arma_grebas_raro.png'),
  @('F:\Dungeon\ARMAMENTO\Guantes comun.png','F:\PROYECTOS\dungeon\images\arma_guantes_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Guantes epico.png','F:\PROYECTOS\dungeon\images\arma_guantes_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Guantes legendario.png','F:\PROYECTOS\dungeon\images\arma_guantes_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Guantes mitico.png','F:\PROYECTOS\dungeon\images\arma_guantes_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Guantes raro.png','F:\PROYECTOS\dungeon\images\arma_guantes_raro.png'),
  @('F:\Dungeon\ARMAMENTO\Mazo comun.png','F:\PROYECTOS\dungeon\images\arma_mazo_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Mazo epico.png','F:\PROYECTOS\dungeon\images\arma_mazo_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Mazo legendario.png','F:\PROYECTOS\dungeon\images\arma_mazo_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Mazo mitico.png','F:\PROYECTOS\dungeon\images\arma_mazo_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Mazo raro.png','F:\PROYECTOS\dungeon\images\arma_mazo_raro.png'),
  @('F:\Dungeon\ARMAMENTO\Pecho comun.png','F:\PROYECTOS\dungeon\images\arma_pecho_comun.png'),
  @('F:\Dungeon\ARMAMENTO\Pecho epico.png','F:\PROYECTOS\dungeon\images\arma_pecho_epico.png'),
  @('F:\Dungeon\ARMAMENTO\Pecho legendario.png','F:\PROYECTOS\dungeon\images\arma_pecho_legendario.png'),
  @('F:\Dungeon\ARMAMENTO\Pecho mitico.png','F:\PROYECTOS\dungeon\images\arma_pecho_mitico.png'),
  @('F:\Dungeon\ARMAMENTO\Pecho raro.png','F:\PROYECTOS\dungeon\images\arma_pecho_raro.png'),
  @('F:\Dungeon\PERSONAJES\Arquero elfo.png','F:\PROYECTOS\dungeon\images\char_arquero_elfo.png'),
  @('F:\Dungeon\PERSONAJES\Arquero humano.png','F:\PROYECTOS\dungeon\images\char_arquero_humano.png'),
  @('F:\Dungeon\PERSONAJES\Clegiro humano.png','F:\PROYECTOS\dungeon\images\char_clerigo_humano.png'),
  @('F:\Dungeon\PERSONAJES\Clerigo elfo.png','F:\PROYECTOS\dungeon\images\char_clerigo_elfo.png'),
  @('F:\Dungeon\PERSONAJES\Fundador caotico elfo.png','F:\PROYECTOS\dungeon\images\char_fundador_elfo.png'),
  @('F:\Dungeon\PERSONAJES\Fundador caotico humano.png','F:\PROYECTOS\dungeon\images\char_fundador_humano.png'),
  @('F:\Dungeon\PERSONAJES\Guerrero Elfo.png','F:\PROYECTOS\dungeon\images\char_guerrero_elfo.png'),
  @('F:\Dungeon\PERSONAJES\Guerrero humano.png','F:\PROYECTOS\dungeon\images\char_guerrero_humano.png'),
  @('F:\Dungeon\PERSONAJES\Mago elfo.png','F:\PROYECTOS\dungeon\images\char_mago_elfo.png'),
  @('F:\Dungeon\PERSONAJES\Mago humano.png','F:\PROYECTOS\dungeon\images\char_mago_humano.png'),
  @('F:\Dungeon\PERSONAJES\Picaro Elfo.png','F:\PROYECTOS\dungeon\images\char_picaro_elfo.png'),
  @('F:\Dungeon\PERSONAJES\Picaro humano.png','F:\PROYECTOS\dungeon\images\char_picaro_humano.png'),
  @('F:\Dungeon\PERSONAJES\Clase secreta Crononauta.png','F:\PROYECTOS\dungeon\images\char_secreto_crononauta.png'),
  @('F:\Dungeon\PERSONAJES\Clase secreta Druida del abismo.png','F:\PROYECTOS\dungeon\images\char_secreto_druida.png'),
  @('F:\Dungeon\PERSONAJES\Clase secreta Estrella Caida.png','F:\PROYECTOS\dungeon\images\char_secreto_estrella-caida.png'),
  @('F:\Dungeon\PERSONAJES\Clase secreta Nigromante.png','F:\PROYECTOS\dungeon\images\char_secreto_nigromante.png'),
  @('F:\Dungeon\PERSONAJES\Clase secreta Paladin.png','F:\PROYECTOS\dungeon\images\char_secreto_paladin.png'),
  @('F:\Dungeon\PERSONAJES\Clase secreta Titan.png','F:\PROYECTOS\dungeon\images\char_secreto_titan.png'),
  @('F:\Dungeon\FONDOS\FONDOS BEBES\Fondo bebe Fenix mitico.png','F:\PROYECTOS\dungeon\images\pet_fondo_baby_fenix-mitico.png'),
  @('F:\Dungeon\FONDOS\FONDOS BEBES\Fondo bebe dragon.png','F:\PROYECTOS\dungeon\images\pet_fondo_baby_dragon-fuego.png'),
  @('F:\Dungeon\FONDOS\FONDOS BEBES\Fondo bebe grifo.png','F:\PROYECTOS\dungeon\images\pet_fondo_baby_grifo.png'),
  @('F:\Dungeon\FONDOS\FONDOS BEBES\Fondo bebe lobo tormenta.png','F:\PROYECTOS\dungeon\images\pet_fondo_baby_lobo-tormenta.png'),
  @('F:\Dungeon\FONDOS\FONDOS BEBES\Fondo bebe pantera sombra.png','F:\PROYECTOS\dungeon\images\pet_fondo_baby_pantera-sombra.png'),
  @('F:\Dungeon\FONDOS\FONDOS BEBES\Fondo bebe rey de la tempestad.png','F:\PROYECTOS\dungeon\images\pet_fondo_baby_rey-tempestad.png'),
  @('F:\Dungeon\FONDOS\FONDOS BEBES\Fondo bebe zorro gigante naturaleza.png','F:\PROYECTOS\dungeon\images\pet_fondo_baby_zorro-naturaleza.png'),
  @('F:\Dungeon\FONDOS\FONDOS MONTURAS\Fondo montura Fenix mitico.png','F:\PROYECTOS\dungeon\images\pet_fondo_mount_fenix-mitico.png'),
  @('F:\Dungeon\FONDOS\FONDOS MONTURAS\Fondo montura dragon.png','F:\PROYECTOS\dungeon\images\pet_fondo_mount_dragon-fuego.png'),
  @('F:\Dungeon\FONDOS\FONDOS MONTURAS\Fondo montura grifo.png','F:\PROYECTOS\dungeon\images\pet_fondo_mount_grifo.png'),
  @('F:\Dungeon\FONDOS\FONDOS MONTURAS\Fondo montura lobo tormenta.png','F:\PROYECTOS\dungeon\images\pet_fondo_mount_lobo-tormenta.png'),
  @('F:\Dungeon\FONDOS\FONDOS MONTURAS\Fondo montura pantera sombra.png','F:\PROYECTOS\dungeon\images\pet_fondo_mount_pantera-sombra.png'),
  @('F:\Dungeon\FONDOS\FONDOS MONTURAS\Fondo montura rey de la tempestad.png','F:\PROYECTOS\dungeon\images\pet_fondo_mount_rey-tempestad.png'),
  @('F:\Dungeon\FONDOS\FONDOS MONTURAS\Fondo montura zorro gigante naturalezaa.png','F:\PROYECTOS\dungeon\images\pet_fondo_mount_zorro-naturaleza.png'),
  @('F:\Dungeon\FONDOS\FONDOS HUEVOS\Fondo huevo Fenix mitico.png','F:\PROYECTOS\dungeon\images\pet_fondo_egg_fenix-mitico.png'),
  @('F:\Dungeon\FONDOS\FONDOS HUEVOS\Fondo huevo Grifo.png','F:\PROYECTOS\dungeon\images\pet_fondo_egg_grifo.png'),
  @('F:\Dungeon\FONDOS\FONDOS HUEVOS\Fondo huevo dragon.png','F:\PROYECTOS\dungeon\images\pet_fondo_egg_dragon-fuego.png'),
  @('F:\Dungeon\FONDOS\FONDOS HUEVOS\Fondo huevo lobo tormenta.png','F:\PROYECTOS\dungeon\images\pet_fondo_egg_lobo-tormenta.png'),
  @('F:\Dungeon\FONDOS\FONDOS HUEVOS\Fondo huevo pantera sombra.png','F:\PROYECTOS\dungeon\images\pet_fondo_egg_pantera-sombra.png'),
  @('F:\Dungeon\FONDOS\FONDOS HUEVOS\Fondo huevo rey de la tempestad.png','F:\PROYECTOS\dungeon\images\pet_fondo_egg_rey-tempestad.png'),
  @('F:\Dungeon\FONDOS\FONDOS HUEVOS\Fondo huevo zorro gigante naturaleza.png','F:\PROYECTOS\dungeon\images\pet_fondo_egg_zorro-naturaleza.png'),
  @('F:\Dungeon\FONDOS\Fondo bestiario.png','F:\PROYECTOS\dungeon\images\fondo_bestiario.png'),
  @('F:\Dungeon\FONDOS\Fondo habilidades.png','F:\PROYECTOS\dungeon\images\fondo_habilidades.png'),
  @('F:\Dungeon\FONDOS\Fondo herrero.png','F:\PROYECTOS\dungeon\images\fondo_herrero.png'),
  @('F:\Dungeon\FONDOS\Fondo historiall.png','F:\PROYECTOS\dungeon\images\fondo_history.png'),
  @('F:\Dungeon\FONDOS\Fondo integraciones.png','F:\PROYECTOS\dungeon\images\fondo_integrations.png'),
  @('F:\Dungeon\FONDOS\Fondo inventario.png','F:\PROYECTOS\dungeon\images\fondo_inventario.png'),
  @('F:\Dungeon\FONDOS\Fondo logros.png','F:\PROYECTOS\dungeon\images\fondo_logros.png'),
  @('F:\Dungeon\FONDOS\Fondo mascotas.png','F:\PROYECTOS\dungeon\images\fondo_pets.png'),
  @('F:\Dungeon\FONDOS\Fondo metas.png','F:\PROYECTOS\dungeon\images\fondo_metas.png'),
  @('F:\Dungeon\FONDOS\Fondo mi dungeon.png','F:\PROYECTOS\dungeon\images\fondo_dungeon-grows.png'),
  @('F:\Dungeon\FONDOS\Fondo misiones.png','F:\PROYECTOS\dungeon\images\fondo_misiones.png'),
  @('F:\Dungeon\FONDOS\Fondo personaje.png','F:\PROYECTOS\dungeon\images\fondo_character.png'),
  @('F:\Dungeon\FONDOS\Fondo runas.png','F:\PROYECTOS\dungeon\images\fondo_runas.png'),
  @('F:\Dungeon\FONDOS\Fondo sala del trono.png','F:\PROYECTOS\dungeon\images\fondo_stats.png'),
  @('F:\Dungeon\FONDOS\Fondo tienda.png','F:\PROYECTOS\dungeon\images\fondo_shop.png')
)

$ok=0; $miss=0
foreach ($pair in $map) {
  if (Test-Path $pair[0]) {
    Copy-Item -Path $pair[0] -Destination $pair[1] -Force
    $ok++
  } else {
    Write-Host "MISS: $($pair[0])"
    $miss++
  }
}
Write-Host "Copiados: $ok   Faltantes: $miss"
