const CACHE = 'dungeon-v196';
const ASSETS = [
  '/',
  '/index.html',
  '/manifest.json',
  '/css/dungeon.css',
  '/css/dungeon-v2.css',
  '/js/config.js',
  '/js/state.js',
  '/js/db.js',
  '/js/hero.js',
  '/js/quests.js',
  '/js/timer.js',
  '/js/inventory.js',
  '/js/spells.js',
  '/js/views.js',
  '/js/ui.js',
  '/js/events.js',
  '/js/oracle.js',
  '/js/shop.js',
  '/js/familiar.js',
  '/js/rpg.js',
  '/js/pets.js',
  '/js/weapons.js',
  '/js/secret_sets.js',
  '/js/goals.js',
  '/js/reputation.js',
  '/js/patterns.js',
  '/js/mechanics.js',
  '/js/character.js',
  '/js/weather.js',
  '/js/dungeon_clock.js',
  '/js/skill_tree.js',
  '/js/bestiary.js',
  '/js/dungeon_grows.js',
  '/js/runes.js',
  '/js/google_fit.js',
  '/js/hero_score.js',
  '/js/push.js',
  '/js/combos.js',
  '/js/habits.js',
  '/js/ruleta.js',
  '/js/duolingo.js',
  '/js/drops.js',
  '/js/daily_goal.js',
  '/js/weekly_summary.js',
  '/js/challenges.js',
  '/js/zones.js',
  '/js/hero_card.js',
  '/js/world_map.js',
  '/js/sala_personal.js',
  '/js/animations.js',
  '/js/effects.js',
  '/js/auth.js',
  '/js/main.js',
  '/images/boss-bg-comun-1.webp',
  '/images/boss-bg-comun-2.webp',
  '/images/boss-bg-raro-1.webp',
  '/images/boss-bg-raro-2.webp',
  '/images/boss-bg-epico-1.webp',
  '/images/boss-bg-epico-2.webp',
  '/images/boss-bg-legendario-1.webp',
  '/images/boss-bg-legendario-2.webp',
  '/images/boss-bg-mitico-1.webp',
  '/images/boss-bg-mitico-2.webp',
  '/images/boss-bg-cataclismo-1.webp',
  '/images/boss-bg-cataclismo-2.webp',
  '/images/boss_arana-gigante.webp',
  '/images/boss_anio-nuevo.webp',
  '/images/boss_behemot-vacio.webp',
  '/images/boss_caballero-espectral.webp',
  '/images/boss_custodio-tiempo.webp',
  '/images/boss_devorador-constelaciones.webp',
  '/images/boss_dragon-tormentas.webp',
  '/images/boss_dragon-obsidiana.webp',
  '/images/boss_arquitecto-vacio.webp',
  '/images/boss_fenix-cenizas.webp',
  '/images/boss_golem-cristal.webp',
  '/images/boss_golem-piedra.webp',
  '/images/boss_halloween.webp',
  '/images/boss_hidra-pesadilla.webp',
  '/images/boss_kraken-abisal.webp',
  '/images/boss_la-que-susurra.webp',
  '/images/boss_demonio-sombras.webp',
  '/images/boss_liche-ancestral.webp',
  '/images/boss_liche-rey.webp',
  '/images/boss_navidad.webp',
  '/images/boss_caballero-esqueleto.webp',
  '/images/boss_ogro-cripta.webp',
  '/images/boss_quimera.webp',
  '/images/boss_serafin-caido.webp',
  '/images/boss_slime-corrosivo.webp',
  '/images/boss_titan-magma.webp',
  '/images/boss_wyvern-hielo.webp',
  /* Rune fragments */
  '/images/runa_fragmento_fuerza.webp',
  '/images/runa_fragmento_vida.webp',
  '/images/runa_fragmento_velocidad.webp',
  '/images/runa_fragmento_arcana.webp',
  '/images/runa_fragmento_xp.webp',
  '/images/runa_fragmento_sombra.webp',
  '/images/runa_fragmento_mitica.webp',
  '/images/runa_fragmento_proteccion.webp',
  /* Complete runes */
  '/images/runa_fuerza.webp',
  '/images/runa_vida.webp',
  '/images/runa_velocidad.webp',
  '/images/runa_arcana.webp',
  '/images/runa_xp.webp',
  '/images/runa_sombra.webp',
  '/images/runa_mitica.webp',
  '/images/runa_proteccion.webp',
  /* Consumables */
  '/images/item_potion.webp',
  '/images/item_scroll.webp',
  '/images/item_amulet.webp',
  '/images/item_xpstone.webp',
  '/images/item_revival.webp',
  '/images/item_hp_minor.webp',
  '/images/item_gold_rush.webp',
  '/images/item_boss_shield.webp',
  '/images/item_xp_scroll_sm.webp',
  /* Spell images */
  '/images/spell_frenzy.webp',
  '/images/spell_speed.webp',
  '/images/spell_berserker.webp',
  '/images/spell_shield.webp',
  '/images/spell_modo-berserker.webp',
  '/images/spell_healing.webp',
  '/images/spell_mente-acero.webp',
  '/images/spell_rayo-arcano.webp',
  '/images/spell_bola-fuego.webp',
  '/images/spell_maldicion-abismal.webp',
  '/images/spell_tormenta-hielo.webp',
  '/images/spell_furia-dragon.webp',
  /* Dungeon rooms */
  '/images/dungeon_sala1.webp',
  '/images/dungeon_sala2.webp',
  '/images/dungeon_sala3.webp',
  '/images/dungeon_sala4.webp',
  '/images/dungeon_sala5.webp',
  '/images/dungeon_sala6.webp',
  '/images/dungeon_sala7.webp',
  '/images/dungeon_sala8.webp',
  '/images/dungeon_sala9.webp',
  /* World map */
  '/images/mapa_mundo.webp',
  /* World map icons */
  '/images/map_ciudadela.webp',
  '/images/map_campo.webp',
  '/images/map_torre.webp',
  '/images/map_fortaleza.webp',
  '/images/map_jardin.webp',
  '/images/map_cripta.webp',
  /* Pet garden */
  '/js/pet_garden.js',
  '/js/boss_battle.js',
  '/images/jardin_fondo.webp',
  /* Pet eggs */
  '/images/pet_egg_zorro-naturaleza.webp',
  '/images/pet_egg_pantera-sombra.webp',
  '/images/pet_egg_lobo-tormenta.webp',
  '/images/pet_egg_grifo.webp',
  '/images/pet_egg_dragon-fuego.webp',
  '/images/pet_egg_fenix-mitico.webp',
  '/images/pet_egg_rey-tempestad.webp',
  /* Pet babies */
  '/images/pet_baby_zorro-naturaleza.webp',
  '/images/pet_baby_pantera-sombra.webp',
  '/images/pet_baby_lobo-tormenta.webp',
  '/images/pet_baby_grifo.webp',
  '/images/pet_baby_dragon-fuego.webp',
  '/images/pet_baby_fenix-mitico.webp',
  '/images/pet_baby_rey-tempestad.webp',
  /* Pet mounts */
  '/images/pet_mount_zorro-naturaleza.webp',
  '/images/pet_mount_pantera-sombra.webp',
  '/images/pet_mount_lobo-tormenta.webp',
  '/images/pet_mount_grifo.webp',
  '/images/pet_mount_dragon-fuego.webp',
  '/images/pet_mount_fenix-mitico.webp',
  '/images/pet_mount_rey-tempestad.webp',
  /* Pet potions */
  '/images/pet_pocion_zorro-naturaleza.webp',
  '/images/pet_pocion_pantera-sombra.webp',
  '/images/pet_pocion_lobo-tormenta.webp',
  '/images/pet_pocion_grifo.webp',
  '/images/pet_pocion_dragon-fuego.webp',
  '/images/pet_pocion_fenix-mitico.webp',
  '/images/pet_pocion_rey-tempestad.webp',
  /* Pet food */
  '/images/pet_alimento_zorro-naturaleza.webp',
  '/images/pet_alimento_pantera-sombra.webp',
  '/images/pet_alimento_lobo-tormenta.webp',
  '/images/pet_alimento_grifo.webp',
  '/images/pet_alimento_dragon-fuego.webp',
  '/images/pet_alimento_fenix-mitico.webp',
  '/images/pet_alimento_rey-tempestad.webp',
  /* Weapons & armor */
  '/images/arma_espada_comun.webp','/images/arma_espada_raro.webp','/images/arma_espada_epico.webp','/images/arma_espada_legendario.webp','/images/arma_espada_mitico.webp',
  '/images/arma_mazo_comun.webp','/images/arma_mazo_raro.webp','/images/arma_mazo_epico.webp','/images/arma_mazo_legendario.webp','/images/arma_mazo_mitico.webp',
  '/images/arma_baculo_comun.webp','/images/arma_baculo_raro.webp','/images/arma_baculo_epico.webp','/images/arma_baculo_legendario.webp','/images/arma_baculo_mitico.webp',
  '/images/arma_arco_comun.webp','/images/arma_arco_raro.webp','/images/arma_arco_epico.webp','/images/arma_arco_legendario.webp','/images/arma_arco_mitico.webp',
  '/images/arma_dagas_comun.webp','/images/arma_dagas_raro.webp','/images/arma_dagas_epico.webp','/images/arma_dagas_legendario.webp','/images/arma_dagas_mitico.webp',
  '/images/arma_pecho_comun.webp','/images/arma_pecho_raro.webp','/images/arma_pecho_epico.webp','/images/arma_pecho_legendario.webp','/images/arma_pecho_mitico.webp',
  '/images/arma_casco_comun.webp','/images/arma_casco_raro.webp','/images/arma_casco_epico.webp','/images/arma_casco_legendario.webp','/images/arma_casco_mitico.webp',
  '/images/arma_botas_comun.webp','/images/arma_botas_raro.webp','/images/arma_botas_epico.webp','/images/arma_botas_legendario.webp','/images/arma_botas_mitico.webp',
  '/images/arma_guantes_comun.webp','/images/arma_guantes_raro.webp','/images/arma_guantes_epico.webp','/images/arma_guantes_legendario.webp','/images/arma_guantes_mitico.webp',
  '/images/arma_grebas_comun.webp','/images/arma_grebas_raro.webp','/images/arma_grebas_epico.webp','/images/arma_grebas_legendario.webp','/images/arma_grebas_mitico.webp',
  /* Character portraits */
  '/images/char_guerrero_humano.webp','/images/char_guerrero_elfo.webp',
  '/images/char_mago_humano.webp','/images/char_mago_elfo.webp',
  '/images/char_arquero_humano.webp','/images/char_arquero_elfo.webp',
  '/images/char_clerigo_humano.webp','/images/char_clerigo_elfo.webp',
  '/images/char_picaro_humano.webp','/images/char_picaro_elfo.webp',
  '/images/char_fundador_humano.webp','/images/char_fundador_elfo.webp',
  /* Secret class portraits */
  '/images/char_secreto_crononauta.webp','/images/char_secreto_paladin.webp',
  '/images/char_secreto_nigromante.webp','/images/char_secreto_titan.webp',
  '/images/char_secreto_druida.webp','/images/char_secreto_estrella-caida.webp',
  /* Pet fondos */
  '/images/pet_fondo_baby_zorro-naturaleza.webp','/images/pet_fondo_baby_pantera-sombra.webp','/images/pet_fondo_baby_lobo-tormenta.webp','/images/pet_fondo_baby_grifo.webp','/images/pet_fondo_baby_dragon-fuego.webp','/images/pet_fondo_baby_fenix-mitico.webp','/images/pet_fondo_baby_rey-tempestad.webp',
  '/images/pet_fondo_mount_zorro-naturaleza.webp','/images/pet_fondo_mount_pantera-sombra.webp','/images/pet_fondo_mount_lobo-tormenta.webp','/images/pet_fondo_mount_grifo.webp','/images/pet_fondo_mount_dragon-fuego.webp','/images/pet_fondo_mount_fenix-mitico.webp','/images/pet_fondo_mount_rey-tempestad.webp',
  '/images/pet_fondo_egg_zorro-naturaleza.webp','/images/pet_fondo_egg_pantera-sombra.webp','/images/pet_fondo_egg_lobo-tormenta.webp','/images/pet_fondo_egg_grifo.webp','/images/pet_fondo_egg_dragon-fuego.webp','/images/pet_fondo_egg_fenix-mitico.webp','/images/pet_fondo_egg_rey-tempestad.webp',
  /* Sala personal furniture */
  '/images/mueble_sillon.webp','/images/mueble_candelabro.webp','/images/mueble_cofre.webp',
  '/images/mueble_espejo.webp','/images/mueble_estanteria.webp','/images/mueble_bola-cristal.webp',
  '/images/mueble_cuadro.webp','/images/mueble_planta.webp','/images/mueble_rack-armas.webp',
  '/images/mueble_vasija.webp',
  /* View backgrounds */
  '/images/fondo_misiones.webp','/images/fondo_metas.webp','/images/fondo_stats.webp',
  '/images/fondo_logros.webp','/images/fondo_history.webp','/images/fondo_shop.webp',
  '/images/fondo_inventario.webp','/images/fondo_pets.webp','/images/fondo_dungeon-grows.webp',
  '/images/fondo_integrations.webp','/images/fondo_character.webp','/images/fondo_habilidades.webp',
  '/images/fondo_runas.webp','/images/fondo_bestiario.webp','/images/fondo_herrero.webp',
  /* Arte integrado 2026-07-03: nav, toolbar, slots, attrs, clases, razas, logros, clima, eventos, temporada, habilidades, mapa zonas, personajes, sets secretos */
  '/images/attr_agilidad.webp',
  '/images/attr_constitucion.webp',
  '/images/attr_fuerza.webp',
  '/images/attr_intelecto.webp',
  '/images/attr_suerte.webp',
  '/images/char_arquero_enano.webp',
  '/images/char_arquero_orco.webp',
  '/images/char_clerigo_enano.webp',
  '/images/char_clerigo_orco.webp',
  '/images/char_fundador_enano.webp',
  '/images/char_fundador_orco.webp',
  '/images/char_guerrero_enano.webp',
  '/images/char_guerrero_orco.webp',
  '/images/char_mago_enano.webp',
  '/images/char_mago_orco.webp',
  '/images/char_picaro_enano.webp',
  '/images/char_picaro_orco.webp',
  '/images/clase_arquero.webp',
  '/images/clase_clerigo.webp',
  '/images/clase_fundador.webp',
  '/images/clase_guerrero.webp',
  '/images/clase_mago.webp',
  '/images/clase_picaro.webp',
  '/images/clima_arcoiris.webp',
  '/images/clima_despejado.webp',
  '/images/clima_eclipse.webp',
  '/images/clima_niebla.webp',
  '/images/clima_tormenta.webp',
  '/images/estacion_invierno.webp',
  '/images/estacion_otono.webp',
  '/images/estacion_primavera.webp',
  '/images/estacion_verano.webp',
  '/images/evento_bendicion.webp',
  '/images/evento_dragon.webp',
  '/images/evento_esfinge.webp',
  '/images/evento_espiritu.webp',
  '/images/evento_maldicion.webp',
  '/images/evento_mercader.webp',
  '/images/evento_pergamino.webp',
  '/images/evento_taberna.webp',
  '/images/evento_tesoro.webp',
  '/images/evento_tormenta-arcana.webp',
  '/images/fondo_sala_personal.webp',
  '/images/habilidad_arquero.webp',
  '/images/habilidad_clerigo.webp',
  '/images/habilidad_fundador.webp',
  '/images/habilidad_guerrero.webp',
  '/images/habilidad_mago.webp',
  '/images/habilidad_picaro.webp',
  '/images/logro_archimago.webp',
  '/images/logro_ascendido.webp',
  '/images/logro_banquero.webp',
  '/images/logro_cronista.webp',
  '/images/logro_dia-gloria.webp',
  '/images/logro_dios-guerra.webp',
  '/images/logro_elite.webp',
  '/images/logro_en-ascenso.webp',
  '/images/logro_en-llamas.webp',
  '/images/logro_eterno.webp',
  '/images/logro_exterminador.webp',
  '/images/logro_forjado-hierro.webp',
  '/images/logro_guerrero-domingo.webp',
  '/images/logro_incansable.webp',
  '/images/logro_indestructible.webp',
  '/images/logro_leyenda.webp',
  '/images/logro_madrugador.webp',
  '/images/logro_maestro-poder.webp',
  '/images/logro_maestro-tiempo.webp',
  '/images/logro_maraton-rojo.webp',
  '/images/logro_mercader.webp',
  '/images/logro_nocturno.webp',
  '/images/logro_plutocrata.webp',
  '/images/logro_primer-pomodoro.webp',
  '/images/logro_primera-sangre.webp',
  '/images/logro_renacido.webp',
  '/images/logro_rico-poder.webp',
  '/images/logro_semana-epica.webp',
  '/images/logro_senor-caos.webp',
  '/images/logro_señor-tiempo.webp',
  '/images/logro_tesoro-arcano.webp',
  '/images/logro_tiempo-infinito.webp',
  '/images/logro_triple-amenaza.webp',
  '/images/logro_veterano.webp',
  '/images/mapa_dungeon_icono.webp',
  '/images/nav_bestiario.webp',
  '/images/nav_config.webp',
  '/images/nav_dungeon.webp',
  '/images/nav_habilidades.webp',
  '/images/nav_historial.webp',
  '/images/nav_integraciones.webp',
  '/images/nav_inventario.webp',
  '/images/nav_logros.webp',
  '/images/nav_mascotas.webp',
  '/images/nav_metas.webp',
  '/images/nav_misiones.webp',
  '/images/nav_mundo.webp',
  '/images/nav_patrones.webp',
  '/images/nav_retos.webp',
  '/images/nav_stats.webp',
  '/images/nav_tienda.webp',
  '/images/raza_elfo.webp',
  '/images/raza_enano.webp',
  '/images/raza_humano.webp',
  '/images/raza_orco.webp',
  '/images/secret_crononauta_arma.webp',
  '/images/secret_crononauta_botas.webp',
  '/images/secret_crononauta_casco.webp',
  '/images/secret_crononauta_grebas.webp',
  '/images/secret_crononauta_guantes.webp',
  '/images/secret_crononauta_pecho.webp',
  '/images/secret_druida_arma.webp',
  '/images/secret_druida_botas.webp',
  '/images/secret_druida_casco.webp',
  '/images/secret_druida_grebas.webp',
  '/images/secret_druida_guantes.webp',
  '/images/secret_druida_pecho.webp',
  '/images/secret_estrella-caida_arma.webp',
  '/images/secret_estrella-caida_botas.webp',
  '/images/secret_estrella-caida_casco.webp',
  '/images/secret_estrella-caida_grebas.webp',
  '/images/secret_estrella-caida_guantes.webp',
  '/images/secret_estrella-caida_pecho.webp',
  '/images/secret_nigromante_arma.webp',
  '/images/secret_nigromante_botas.webp',
  '/images/secret_nigromante_casco.webp',
  '/images/secret_nigromante_grebas.webp',
  '/images/secret_nigromante_guantes.webp',
  '/images/secret_nigromante_pecho.webp',
  '/images/secret_paladin_arma.webp',
  '/images/secret_paladin_botas.webp',
  '/images/secret_paladin_casco.webp',
  '/images/secret_paladin_grebas.webp',
  '/images/secret_paladin_guantes.webp',
  '/images/secret_paladin_pecho.webp',
  '/images/secret_titan_arma.webp',
  '/images/secret_titan_botas.webp',
  '/images/secret_titan_casco.webp',
  '/images/secret_titan_grebas.webp',
  '/images/secret_titan_guantes.webp',
  '/images/secret_titan_pecho.webp',
  '/images/slot_arma-principal.webp',
  '/images/slot_arma-secundaria.webp',
  '/images/slot_botas.webp',
  '/images/slot_casco.webp',
  '/images/slot_grebas.webp',
  '/images/slot_guantes.webp',
  '/images/slot_pecho.webp',
  '/images/tool_cronica.webp',
  '/images/tool_hechizos.webp',
  '/images/tool_herrero.webp',
  '/images/tool_ruleta.webp',
  '/images/tool_slots.webp',
  '/images/tool_timer.webp',
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('push', e => {
  const data = e.data?.json() || {};
  e.waitUntil(
    self.registration.showNotification(data.title || 'Arcanum', {
      body:    data.body  || '',
      icon:    'https://stdedxhxxoyostymldqn.supabase.co/storage/v1/object/public/assets/dungeon/logo-icon.png',
      badge:   'https://stdedxhxxoyostymldqn.supabase.co/storage/v1/object/public/assets/dungeon/logo-icon.png',
      vibrate: [200, 100, 200],
      data:    { url: data.url || '/' },
    })
  );
});

self.addEventListener('notificationclick', e => {
  e.notification.close();
  e.waitUntil(
    clients.matchAll({ type:'window', includeUncontrolled:true }).then(list => {
      const existing = list.find(c => c.url.includes(self.location.origin));
      if (existing) { existing.focus(); existing.navigate(e.notification.data?.url || '/'); }
      else clients.openWindow(e.notification.data?.url || '/');
    })
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || !e.request.url.startsWith(self.location.origin)) return;
  if (e.request.url.includes('supabase.co')) return;
  // HTML: network-first para siempre tener la versiÃ³n mÃ¡s reciente
  if (e.request.headers.get('accept')?.includes('text/html')) {
    e.respondWith(
      fetch(e.request).catch(() => caches.match(e.request))
    );
    return;
  }
  e.respondWith(
    caches.match(e.request).then(cached => cached || fetch(e.request))
  );
});





